[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "inmotion"
version = "0.2.2"
description = "An SDK for integrating with inMotion API"
authors = [{ name = "Jason Waring", email = "jason@softwaringsolutions.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
          "numpy",
          "pycryptodome",
          "python-dotenv",
          "pandas",
          "urllib3",
          "requests",
          "marshmallow",
          "marshmallow_dataclass"]
classifiers = ["Private :: Do Not Upload"]

[project.optional-dependencies]
dev = ["pytest", "tox"]

[project.scripts]
test = "scripts.test:main"

[tool.hatch.build]
include = ["inmotion"]
